main:
  TeamSpeakIp: 1.2.3.4
  TeamSpeakPort: 9987
  QueryPort: 10011
  QueryUsername: admin
  QueryPassword: '123456'
messages:
  msg_join: '&e%client_nickname% &ahas joined TeamSpeak'
  msg_quit: '&e%client_nickname% &ahas left TeamSpeak'
  msg_servermsg: '[&cTS&f][&e%client_nickname%&f] &a%msg%'
  msg_list: '&aCurrently online: &e'
  msg_mute: '&aYou are now muted.'
  msg_unmute: '&aYou aren''t muted anymore.'
