main:
  TeamSpeakIp: 1.2.3.4
  TeamSpeakPort: 9987
  QueryPort: 10011
  QueryUsername: admin
  QueryPassword: '123456'
teamspeak:
  BroadcastNickname: Minecraft
  ListenToServerEvents: true
  ListenToServerBroadcasts: true
  ListenToChannel: false
  ListenToChannelChat: false
  ChannelID: 0
messages:
  Join: '&e%client_nickname% &ahas joined TeamSpeak'
  Quit: '&e%client_nickname% &ahas left TeamSpeak'
  ServerMsg: '[&cTS&f] &e%client_nickname%: &a%msg%'
  ChannelMsg: '&e%client_nickname%: &f%msg%'
  OnlineList: '&aCurrently online: &e%list%'
  Mute: '&aYou are now muted.'
  Unmute: '&aYou aren''t muted anymore.'
