name: BukkitSpeak
version: '0.25'
description: 'This plugin will display Teamspeak 3 server joins, quits and messages in Minecraft.'
main: net.but2002.minecraft.BukkitSpeak.BukkitSpeak
load: POSTWORLD
author: 'greycap'
authors: [but2002, Firedroide]
database: false