name: BukkitSpeak
version: '0.50'
description: 'This plugin will display Teamspeak 3 server joins, quits and messages in Minecraft.'
main: net.but2002.minecraft.BukkitSpeak.BukkitSpeak
load: POSTWORLD
author: 'Firedroide'
authors: [but2002, greycap, deathmarine]
database: false
commands:
  ts:
    description: BukkitSpeak commands
    usage: Type /ts for help.
  tsa:
    description: BukkitSpeak admin commands
    usage: Type /tsa for help.
permissions:
  bukkitspeak.*:
    description: Gives access to all BukkitSpeak commands and messages.
    default: op
    children:
      bukkitspeak.commands.*: true
      bukkitspeak.messages.*: true
  bukkitspeak.moderator:
    description: Gives access to all user commands, all the messages and some admin commands.
    children:
      bukkitspeak.commands.user: true
      bukkitspeak.commands.channelkick: true
      bukkitspeak.commands.reload: true
  bukkitspeak.user:
    description: Gives access to most of the user commands and all messages.
    children:
      bukkitspeak.commands.list: true
      bukkitspeak.commands.mute: true
      bukkitspeak.commands.chat: true
      bukkitspeak.commands.pm: true
      bukkitspeak.commands.info: true
      bukkitspeak.messages.*: true
  bukkitspeak.commands.*:
    description: Gives access to all BukkitSpeak commands.
    children:
      bukkitspeak.commands.user: true
      bukkitspeak.commands.admin: true
  bukkitspeak.commands.user:
    description: Gives access to all user commands.
    children:
      bukkitspeak.commands.list: true
      bukkitspeak.commands.mute: true
      bukkitspeak.commands.broadcast: true
      bukkitspeak.commands.chat: true
      bukkitspeak.commands.pm: true
      bukkitspeak.commands.poke: true
      bukkitspeak.commands.info: true
      bukkitspeak.commands.status: true
  bukkitspeak.commands.admin:
    description: Gives access to all admin commands.
    children:
      bukkitspeak.commands.kick: true
      bukkitspeak.commands.channelkick: true
      bukkitspeak.commands.reload: true
  bukkitspeak.commands.list:
    description: Allows you to use /ts list
  bukkitspeak.commands.mute:
    description: Allows you to use /ts mute
  bukkitspeak.commands.broadcast:
    description: Allows you to use /ts broadcast message
  bukkitspeak.commands.chat:
    description: Allows you to use /ts chat message
  bukkitspeak.commands.pm:
    description: Allows you to use /ts pm target message
  bukkitspeak.commands.poke:
    description: Allows you to use /ts poke target message
  bukkitspeak.commands.info:
    description: Allows you to use /ts info
  bukkitspeak.commands.status:
    description: Allows you to use /ts status  
  bukkitspeak.commands.kick:
    description: Allows you to use /ts reload
  bukkitspeak.commands.channelkick:
    description: Allows you to use /ts reload
  bukkitspeak.commands.reload:
    description: Allows you to use /ts reload
  bukkitspeak.messages.*:
    description: Allows you to see all messages.
    children:
      bukkitspeak.messages.join: true
      bukkitspeak.messages.leave: true
      bukkitspeak.messages.channelenter: true
      bukkitspeak.messages.channelleave: true
      bukkitspeak.messages.broadcast: true
      bukkitspeak.messages.chat: true
      bukkitspeak.messages.pm: true
  bukkitspeak.messages.join:
    description: Displays you a message when somebody joined TeamSpeak.
  bukkitspeak.messages.leave:
    description: Displays you a message when somebody left TeamSpeak.
  bukkitspeak.messages.channelenter:
    description: Displays you a message when somebody entered the channel BukkitSpeak is listening to.
  bukkitspeak.messages.channelleave:
    description: Displays you a message when somebody left the channel BukkitSpeak is listening to.
  bukkitspeak.messages.broadcast:
    description: Shows you a broadcasts on TeamSpeak.
  bukkitspeak.messages.chat:
    description: Shows you chat messages in the channel BukkitSpeak is listening to.
  bukkitspeak.messages.pm:
    description: Shows you a message, if somebody replies to your private message.
