main:
  TeamSpeakIp: 1.2.3.4
  TeamSpeakPort: 9987
  QueryPort: 10011
  QueryUsername: admin
  QueryPassword: '123456'
teamspeak:
  TeamspeakNickname: Minecraft
  ConsoleName: '&9Server'
  
  # Only required if you use the channel functions!
  ChannelID: 0
  ChannelPassword: ''
  
  # Can only be true or false
  ListenToServerEvents: true
  ListenToServerBroadcasts: true
  ListenToChannel: true
  ListenToChannelChat: true
  ListenToPrivateMessages: true
  AllowLinksInMessages: true
  
  # Can be either 'server', 'channel' or 'none'
  SendChatToTeamspeak: none
  
  # Can only be true or false
  LogChatInConsole: true
  
  # Default reason for bans and (channel) kicks
  DefaultReason: '-'
  
  # Debug Mode
  # Use if the plugin doesn't work at all
  # Or for posting error logs in the forum
  Debug: false

plugin-interaction:
  Factions:
    # If Factions is enabled, should only public chat be sent to TeamSpeak?
    public-only: true
  Herochat:
    # Do we want to enable support for Herochat?
    enabled: false
    # Which channel do we want us to use?
    channel: Global
    # Should events on TeamSpeak (Enter, Leave, Channel changed)
    # also be sent to this channel?
    SendTeamspeakEventsToChannel: false
  mcMMO:
    # Only applies if mcMMO is enabled on the server.
    # Should party chat be filtered out?
    FilterPartyChat: true
    # Should admin chat be filtered out?
    FilterAdminChat: true
